### ISSUE TITLE
spatial tutorial about np.concatenate

### ISSUE THREAD

**Issue by caiquanyou** [scverse/scanpy-tutorials#33]
When  I  running the spatial tutorial and get some trouble in thie step below:
embedding_anterior = np.concatenate(integrated_anterior, axis=0)
 I run this code and python just keep running and got no result,use Ctrl + C to end and get the traceback below:
Traceback (most recent call last):
  File "/root/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3418, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-5-d05399c50c91>", line 1, in <module>
    embedding = np.concatenate(integrated, axis=0)
  File "<__array_function__ internals>", line 5, in concatenate
  File "/root/anaconda3/lib/python3.8/site-packages/anndata/_core/anndata.py", line 1088, in __getitem__
    return AnnData(self, oidx=oidx, vidx=vidx, asview=True)
  File "/root/anaconda3/lib/python3.8/site-packages/anndata/_core/anndata.py", line 305, in __init__
    self._init_as_view(X, oidx, vidx)
  File "/root/anaconda3/lib/python3.8/site-packages/anndata/_core/anndata.py", line 358, in _init_as_view
    self._remove_unused_categories(adata_ref.var, var_sub, uns_new)
  File "/root/anaconda3/lib/python3.8/site-packages/anndata/_core/anndata.py", line 1092, in _remove_unused_categories
    if not is_categorical_dtype(df_full[k]):
  File "/root/anaconda3/lib/python3.8/site-packages/pandas/core/frame.py", line 2878, in __getitem__
    return self._get_item_cache(key)
  File "/root/anaconda3/lib/python3.8/site-packages/pandas/core/generic.py", line 3540, in _get_item_cache
    loc = self.columns.get_loc(item)
  File "/root/anaconda3/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 2895, in get_loc
    return self._engine.get_loc(casted_key)
KeyboardInterrupt

**Comment by giovp** [comment]
hi @caiquanyou , thanks for the issue and sorry for the late reply. Can you please update to latest scanpy and scanorama (there was an update) and write here your pacakge versions?
```python
import scanpy
sc.logging.print_header()
```

also, the notebook was recently updated, see #32 , can you please have a look at that version ? Thank you!
